= IETF BibXML legacy data backup

WARNING: This is a **BACKUP** of legacy data. 
The data in this repository **IS FROZEN** as of 2022-06-21, superseded by the
new BibXML Service at https://bib.ietf.org.

WARNING: Please do not change data in this repository unless you know for sure
what is being done.

NOTE: The data in this repository used to be managed by the
bibxml-data-archive-sync workflow automatically. 

This work is created under the IETF/Ribose BibXML service SOW.

== Purpose

This repository is a mirror to the IETF BibXML legacy datasets,
located at `xml2rfc.tools.ietf.org::xml2rfc.bibxml` (publicly accessible).

This repository is used to facilitate legacy path mapping from
legacy BibXML file names to identifiers in the new BibXML service.

== WARNING

If you make any changes to this repository outside of the protected paths, your
changes will be *wiped out* on the next auto-update.

The protected paths (i.e. where your changes will persist) are:

* `.git*`
* `README.*`

== Licence

BSD 3-clause license.
